version: '3.9'

services:
  instance:
    container_name: lambda-function-project-container
    build:
      context: .
      dockerfile: Dockerfile-local
    volumes:
      - ./htmlcov:/project/htmlcov
      - ./src/lambda_function.py:/project/lambda_function.py
      - ./tests:/project/tests
      - ./.coveragerc:/project/.coveragerc
    env_file:
      - .env
    command: ["tail", "-f", "/dev/null"]  # To keep the container instance alive
